
# Define variables
# NOTE: executable should be a full path
LOGS_DIR=/fast/najroldi/logs/llm
executable=/home/najroldi/llm_pretrain/cluster/condor/multi_gpu/run.sh

# Job specific vars
config=config/config.yaml
n_jobs=8

# Args
arguments = $(config) $(Process)

# Logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Specs
request_memory = 1000000
request_cpus = 96
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")

queue $(n_jobs)
