
deterministic: False
seed: 1996

cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

trainset_path: "/fast/najroldi/data/finewebedu2/train"
vocab_size: 50257
seq_len: 1024
num_workers: 4

sampler: 'stateful_random'
sampler_seed: 1996

eval: True
validset_path: "/fast/najroldi/data/finewebedu2/val"
eval_every_steps: 10

model: 'transformer'
d_model: 768
expand: '8/3'
n_layers: 12
n_heads: 12
mlp_class: 'glu'
tie_embeddings: True
torch_compile: True

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps)
steps_budget: 9400

# note 1: this is micro batch size if grad_accumulation_steps>1
# note 2: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
micro_batch_size: 64
grad_accumulation_steps: 4

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'

optim: 'adamw'
fused_optim: True
lr: 1.e-4
weight_decay: 0.01
beta1: 0.9
beta2: 0.95
grad_clip: 0.01
eps: 1.e-12

scheduler: 'warmup_cosine'
warmup_steps: 0.01
cooldown_steps: null
lr_start: 1.e-10
lr_end: null
lr_end_pct: 0.0

log_every_steps: 10
print_progress: False

use_wandb: False
wandb_watch: False
wandb_project: 'wa_lm_2'
wandb_dir: '/fast/najroldi/logs/wa_lm_2/wandb'
wandb_run_name: 'test_run'
exp_name: 'test_run'

resume: False
resume_step: null
resume_exp_name: null

out_dir: '/fast/najroldi/exp/wa_lm_2'
save_last_checkpoint: True
save_intermediate_checkpoints: True
save_every_steps: 10
over_write: True
