
#######################################################
## This is designed to fit on 4xGPUs, 80GB VRAM
## Total bsz: 8 * 16 * 4 = 512, 0.5BT
## Steps: 18_800 -> 18_800 * 512 * 10224 = 10B tokens
#######################################################

deterministic: False
seed: 1996

cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

trainset_path: "/fast/najroldi/data/finewebedu2/train"
vocab_size: 50257
seq_len: 2048
num_workers: 4

sampler: 'stateful_random'
sampler_seed: 1996

eval: True
validset_path: "/fast/najroldi/data/finewebedu2/val"
eval_every_steps: 80

model: 'transformer'
d_model: 2048
expand: '8/3'
n_layers: 24
n_heads: 16
mlp_class: 'glu'
tie_embeddings: False
torch_compile: True

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps)
steps_budget: 9400

# note 1: this is micro batch size if grad_accumulation_steps>1
# note 2: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
micro_batch_size: 4
grad_accumulation_steps: 16

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'

optim: 'adamw'
fused_optim: True
lr: [1.e-4, 3.e-4, 1.e-3, 3.e-3, 1.e-2]
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
eps: 1.e-12

scheduler: 'warmup_cosine'
warmup_steps: [0.01, 0.1]
cooldown_steps: null
lr_start: 1.e-10
lr_end: null
lr_end_pct: [0.1, 0.0]

log_every_steps: 80
print_progress: False

use_wandb: True
wandb_watch: False
check_existing_wandb_run: False
wandb_project: 'wa_lm_2'
wandb_dir: '/fast/najroldi/logs/wa_lm_2/wandb'
wandb_run_name: 'sweep_420M_01'
exp_name: 'sweep_420M_01'

resume: False
resume_step: null
resume_exp_name: null

out_dir: '/fast/najroldi/exp/wa_lm_2'
save_last_checkpoint: False
save_intermediate_checkpoints: False
save_every_steps: null
over_write: True
