
deterministic: False
seed: 1996
sampler_seed: 1996

cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

# avg
eval_ckpt_folder: "/fast/najroldi/exp/llm/plm_save_best_01/job_idx_0"
avg_start_step: 0
avg_every_steps: 60
avg_scheme: "LAWA"
lawa_queue_len: 5

trainset_path: "/fast/najroldi/data/lm/fineweb/fw_20B_tokens_ctx1024/train"
vocab_size: 50257
seq_len: 1024
sampler: 'random'
sampler_seed: 1996
num_workers: 4

eval: True
validset_path: "/fast/najroldi/data/lm/fineweb/fw_20B_tokens_ctx1024/valid"
eval_every_steps: 192

model: 'transformer'
d_model: 768
expand: '8/3'
n_layers: 12
n_heads: 12
mlp_class: 'glu'
tie_embeddings: True
torch_compile: True

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps)
steps_budget: 19200

# note 1: this is micro batch size if grad_accumulation_steps>1
# note 2: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
micro_batch_size: 64
grad_accumulation_steps: 1

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'

optim: 'adamw'
fused_optim: True
lr: 0.01
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
eps: 1.e-20

scheduler: 'warmup_cosine'
warmup_steps: 700
cooldown_steps: null
lr_start: 1.e-10
lr_end: null
lr_end_pct: 0.001

log_every_steps: 48
print_progress: False

use_wandb: True
wandb_watch: False
wandb_project: 'wa_lm'
wandb_dir: '/fast/najroldi/logs/wa_lm/wandb'
wandb_run_name: 'plainLM_eval_LAWA_01'
exp_name: 'plainLM_eval_LAWA_01'
check_existing_wandb_run: True

resume: False
resume_micro_step: null
resume_exp_name: null

out_dir: '/fast/najroldi/exp/llm'
save_last_checkpoint: False
save_intermediate_checkpoints: False
save_every_steps: null
over_write: False
